defmodule Helpdesk.Repo.Migrations.Files do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:files, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text)
      add(:csv_column_mappings, {:array, :map})
    end
  end

  def down do
    drop(table(:files))
  end
end
