defmodule Helpdesk.Repo.Migrations.DbChanges do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:managers, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text)
    end

    create table(:files, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:manager_id, :uuid)
      add(:name, :text)
      add(:enabled, :boolean)
    end
  end

  def down do
    drop(table(:files))

    drop(table(:managers))
  end
end
